### ISSUE TITLE
System.PlatformNotSupportedException when creating payment

### ISSUE THREAD

**Issue by PetteriFischerLPF** [paytrail/paytrail-dotnet-sdk#22]
Hello!

I am new to Paytrail and try to get the payment providers.

The code below always gives an exception: "System.PlatformNotSupportedException: Operation is not supported on this platform".

         public static IList<Provider> GetProviderList()
        {
            var payTrailClient = new PayTrailClient("375917", "SAIPPUAKAUPPIAS", "PowerPlaza");

            var paymentRequest = GetPaymentRequest();

            var paymentResponse = payTrailClient.CreatePayment(paymentRequest);
            if (!string.IsNullOrEmpty(paymentResponse.ReturnMessage))
            {
                // We always end up here with the message "System.PlatformNotSupportedException: Operation is not supported on this platform"
                throw new Exception(paymentResponse.ReturnMessage);
            }

            var providers = paymentResponse.Data.Providers;

            return providers.ToList();
        }

        private static PaymentRequest GetPaymentRequest()
        {
            var paymentRequest = new PaymentRequest();
            paymentRequest.Stamp = Guid.NewGuid().ToString();
            paymentRequest.Currency = "EUR";
            paymentRequest.Language = "FI";
            paymentRequest.DeliveryAddress = new Address
            {
                StreetAddress = "Mannerheimintie 1",
                PostalCode = "00100",
                City = "Helsinki",
                Country = "FI"
            };
            paymentRequest.InvoicingAddress = paymentRequest.DeliveryAddress;
            paymentRequest.Reference = "123456789";
            paymentRequest.OrderId = "4711";

            paymentRequest.Customer = new Customer
            {
                FirstName = "Matti",
                LastName = "Meikalainen",
                Email = "Matti.Meikalainen@test.fi",
                Phone = "0505034711",
                VatId = "010101-0101",
                CompanyName = "Company Oy",
            };

            paymentRequest.Items = new List<Item>()
            {
                new Item()
                {
                    UnitPrice = 100,
                    Units = 1,
                    VatPercentage = 24,
                    ProductCode = "1234",
                }
            }.ToArray();
            paymentRequest.Groups = ["mobile", "creditcard"];
            paymentRequest.Amount = 100;
            paymentRequest.UsePricesWithoutVat = false;

            paymentRequest.RedirectUrls = new CallbackUrl
            {
                Success = "https://localhost:7227/Payment/Success",
                Cancel = "https://localhost:7227/Payment/Cancel",
            };

            paymentRequest.CallbackUrls = new CallbackUrl
            {
                Success = "https://localhost:7227/Payment/Success",
                Cancel = "https://localhost:7227/Payment/Cancel",
            };

            return paymentRequest;
        }

**Comment by loueranta-paytrail** [comment]
@PetteriFischerLPF: According to Microsoft forums the "Operation is not supported on this platform" error means the function was ported to .net core, but requires operating system support and was not implemented on the selected build target platform.

On which operating system are you experiencing this problem? 
And could you provide us with stack trace?

**Comment by PetteriFischerLPF** [comment]
I am running this on Windows 10 and Chrome Browser. It is a Blazor WASM application. 

The paymentResponse.ReturnMessage is this:
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Net.Http.BrowserHttpHandler.set_UseCookies(Boolean value)
   at System.Net.Http.HttpClientHandler.set_UseCookies(Boolean value)
   at RestSharp.RestClient.ConfigureHttpMessageHandler(HttpClientHandler handler, ReadOnlyRestClientOptions options)
   at RestSharp.RestClient.<>c__DisplayClass21_0.<.ctor>g__GetClient|0()
   at RestSharp.RestClient..ctor(RestClientOptions options, ConfigureHeaders configureDefaultHeaders, ConfigureSerialization configureSerialization, Boolean useClientFactory)
   at RestSharp.RestClient..ctor(ConfigureRestClient configureRestClient, ConfigureHeaders configureDefaultHeaders, ConfigureSerialization configureSerialization, Boolean useClientFactory)
   at Paytrail_dotnet_sdk.PayTrailClient.CreatePayment(String bodyContent)
   at Paytrail_dotnet_sdk.PayTrailClient.CreatePayment(PaymentRequest paymentRequest)

Could it be that Blazor WASM is not supported by this SDK?

**Comment by OttiaDevsPT** [comment]
Hey @PetteriFischerLPF, it looks like your guess is spot on. Blazor WASM apps run in a web browser sandbox with certain limitations compared to server-side .NET applications. One such limitation is that browser-based HTTP handlers (like BrowserHttpHandler) have restrictions on managing cookies. This is likely due to security and privacy considerations within the browser environment.

**Comment by PetteriFischerLPF** [comment]
Ok, I will use this SDK only in the backend of our application.
