### ISSUE TITLE
Add Support for VAT rate as decimal value to support new base VAT rate in Finland

### ISSUE THREAD

**Issue by obetsak** [paytrail/paytrail-dotnet-sdk#34]
Finland is changing the base VAT from 24% to 25,5% in september
https://www.roschier.com/newsroom/finnish-vat-rate-to-increase-to-25-5-starting-september-2024

the .net sdk only support int as VATpercentage. The new paytrail api support VATpercentage as float 0-100 with . as decimaldivider

**Comment by kotivuori** [comment]
Thanks for reporting, this will be updated asap

**Comment by kotivuori** [comment]
@obetsak This was updated with latest release 1.0.14
